
import javax.swing.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author beeel
 */
public class MyFrame extends javax.swing.JFrame {
    
    private Game game;

    /**
     * Creates new form NewJFrame02
     */
    public MyFrame(Game game) {
        this.game = game;
        initComponents();
        setResizable(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jDialog2 = new javax.swing.JDialog();
        optionPanel = new javax.swing.JPanel();
        optionOne = new javax.swing.JButton();
        optionTwo = new javax.swing.JButton();
        optionThree = new javax.swing.JButton();
        optionTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        westPanel = new javax.swing.JPanel();
        easyButton = new javax.swing.JButton();
        mediumButton = new javax.swing.JButton();
        hardButton = new javax.swing.JButton();
        buttomsPanel = new javax.swing.JPanel();
        northButton = new javax.swing.JButton();
        southButton = new javax.swing.JButton();
        westButton = new javax.swing.JButton();
        eastButton = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        terminalTextArea = new javax.swing.JTextArea();
        southPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textCommands = new javax.swing.JTextArea();
        putButton = new javax.swing.JButton();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        mapPanel = new javax.swing.JPanel();
        mapLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mapMenuBar = new javax.swing.JMenu();
        openMap = new javax.swing.JMenuItem();
        closeMap = new javax.swing.JMenuItem();
        helpMenuBar = new javax.swing.JMenu();
        itemsInTheRoom = new javax.swing.JMenuItem();
        itemsOnTheBackpack = new javax.swing.JMenuItem();
        biomaDescription = new javax.swing.JMenuItem();
        directions = new javax.swing.JMenuItem();
        oxygenBar = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        cleanTerminalButton = new javax.swing.JButton();
        itemsDescription = new javax.swing.JMenuItem();
        takeButton = new javax.swing.JButton();

        jMenuItem1.setText(" ");

        optionPanel.setBackground(new java.awt.Color(0, 0, 0));

        optionOne.setBackground(new java.awt.Color(153, 0, 0));
        optionOne.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        optionOne.setForeground(new java.awt.Color(255, 255, 255));
        optionOne.setText("Option 1");
        optionOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionOneActionPerformed(evt);
            }
        });

        optionTwo.setBackground(new java.awt.Color(153, 0, 0));
        optionTwo.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        optionTwo.setForeground(new java.awt.Color(255, 255, 255));
        optionTwo.setText("Option 2");
        optionTwo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionTwoActionPerformed(evt);
            }
        });

        optionThree.setBackground(new java.awt.Color(153, 0, 0));
        optionThree.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        optionThree.setForeground(new java.awt.Color(255, 255, 255));
        optionThree.setText("Option 3");
        optionThree.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionThreeActionPerformed(evt);
            }
        });

        optionTextArea.setBackground(new java.awt.Color(0, 0, 0));
        optionTextArea.setColumns(20);
        optionTextArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        optionTextArea.setForeground(new java.awt.Color(255, 255, 255));
        optionTextArea.setRows(5);
        jScrollPane3.setViewportView(optionTextArea);

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addComponent(optionOne)
                        .addGap(18, 18, 18)
                        .addComponent(optionTwo)
                        .addGap(18, 18, 18)
                        .addComponent(optionThree)
                        .addGap(39, 39, 39))))
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(optionTwo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(optionOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optionThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setLayout(new java.awt.GridLayout()); 

        westPanel.setBackground(new java.awt.Color(0, 0, 0));
        
        easyButton.setBackground(new java.awt.Color(51, 102, 0));
        easyButton.setForeground(new java.awt.Color(255, 255, 255));
        easyButton.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        easyButton.setText("Easy");
        easyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyButtonActionPerformed(evt);
            }
        });

        mediumButton.setBackground(new java.awt.Color(153, 153, 0));
        mediumButton.setForeground(new java.awt.Color(255, 255, 255));
        mediumButton.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        mediumButton.setText("Medium");
        mediumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumButtonActionPerformed(evt);
            }
        });

        hardButton.setBackground(new java.awt.Color(153, 0, 0));
        hardButton.setForeground(new java.awt.Color(255, 255, 255));
        hardButton.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        hardButton.setText("Hard");
        hardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardButtonActionPerformed(evt);
            }
        });

        oxygenBar.setBackground(new java.awt.Color(0, 0, 0));
        oxygenBar.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        oxygenBar.setForeground(new java.awt.Color(255, 255, 255));
        oxygenBar.setText("Oxigênio:");
        
        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/play button.png"))); // NOI18N
        playButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        pauseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pause button.png"))); // NOI18N
        pauseButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });
        
        cleanTerminalButton.setBackground(new java.awt.Color(0, 153, 153));
        cleanTerminalButton.setForeground(new java.awt.Color(255, 255, 255));
        cleanTerminalButton.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        cleanTerminalButton.setText("Clean Terminal");
        cleanTerminalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanTerminalButtonActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout westPanelLayout = new javax.swing.GroupLayout(westPanel);
        westPanel.setLayout(westPanelLayout);
        westPanelLayout.setHorizontalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(easyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mediumButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(oxygenBar)
            .addGroup(westPanelLayout.createSequentialGroup()
                .addGroup(westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(westPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(westPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cleanTerminalButton)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        westPanelLayout.setVerticalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(easyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mediumButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hardButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cleanTerminalButton)
                .addGap(18, 18, 18)
                .addComponent(oxygenBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playButton)
                    .addComponent(pauseButton))
                .addGap(22, 22, 22))
        );
        
        buttomsPanel.setBackground(new java.awt.Color(0, 0, 0));

        northButton.setBackground(new java.awt.Color(204,102,0));
        northButton.setForeground(new java.awt.Color(255, 255, 255));
        northButton.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        northButton.setText("North");
        northButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                northButtonActionPerformed(evt);
            }
        });

        southButton.setBackground(new java.awt.Color(204,102,0));
        southButton.setForeground(new java.awt.Color(255, 255, 255));
        southButton.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        southButton.setText("South");
        southButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                southButtonActionPerformed(evt);
            }
        });

        westButton.setBackground(new java.awt.Color(204,102,0));
        westButton.setForeground(new java.awt.Color(255, 255, 255));
        westButton.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        westButton.setText("West");
        westButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                westButtonActionPerformed(evt);
            }
        });

        eastButton.setBackground(new java.awt.Color(204,102,0));
        eastButton.setForeground(new java.awt.Color(255, 255, 255));
        eastButton.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        eastButton.setText("East");
        eastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eastButtonActionPerformed(evt);
            }
        });
        
                
            javax.swing.GroupLayout buttomsPanelLayout = new javax.swing.GroupLayout(buttomsPanel);
        buttomsPanel.setLayout(buttomsPanelLayout);
        buttomsPanelLayout.setHorizontalGroup(
            buttomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttomsPanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(northButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(southButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(westButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eastButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        buttomsPanelLayout.setVerticalGroup(
            buttomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(westButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(eastButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(northButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(southButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        terminalTextArea.setBackground(new java.awt.Color(0, 0, 0));
        terminalTextArea.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        terminalTextArea.setColumns(20);
        terminalTextArea.setForeground(new java.awt.Color(255, 255, 255));
        terminalTextArea.setRows(5);
        jScrollPane2.setViewportView(terminalTextArea);

      javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))          
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
        );


        southPanel.setBackground(new java.awt.Color(0, 0, 0));

        textCommands.setBackground(new java.awt.Color(0, 0, 0));
        textCommands.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        textCommands.setColumns(20);
        textCommands.setForeground(new java.awt.Color(255, 255, 255));
        textCommands.setRows(5);
        textCommands.setText("Type Here The Item You Want");
      
        jScrollPane1.setViewportView(textCommands);

        putButton.setBackground(new java.awt.Color(204, 204, 0));
        putButton.setForeground(new java.awt.Color(255, 255, 255));
        putButton.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        putButton.setText("Put");
        putButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                putButtonActionPerformed(evt);
            }
        });
        
        takeButton.setBackground(new java.awt.Color(204, 204, 0));
        takeButton.setForeground(new java.awt.Color(255, 255, 255));
        takeButton.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        takeButton.setText("Take");
        takeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeButtonActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout southPanelLayout = new javax.swing.GroupLayout(southPanel);
        southPanel.setLayout(southPanelLayout);
        southPanelLayout.setHorizontalGroup(
            southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(southPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(putButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(takeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        southPanelLayout.setVerticalGroup(
            southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(southPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(southPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(putButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(takeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        titlePanel.setBackground(new java.awt.Color(255, 255, 255));
        
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Title.jpeg"))); // NOI18N

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addComponent(titleLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mapPanelLayout = new javax.swing.GroupLayout(mapPanel);
        mapPanel.setLayout(mapPanelLayout);
        mapPanelLayout.setHorizontalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mapPanelLayout.setVerticalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        mapLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/map.jpg"))); // NOI18N

        mapMenuBar.setText("Map");

        openMap.setText("Open");
        openMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMapActionPerformed(evt);
            }
        });
        mapMenuBar.add(openMap);

        closeMap.setText("Close");
        closeMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMapActionPerformed(evt);
            }
        });
        mapMenuBar.add(closeMap);

        jMenuBar1.add(mapMenuBar);

        helpMenuBar.setText("Help");

        itemsInTheRoom.setText(" \n Items in the Room");
        itemsInTheRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsInTheRoomActionPerformed(evt);
            }
        });
        helpMenuBar.add(itemsInTheRoom);

        itemsOnTheBackpack.setText(" \n Items on the Backpack");
        itemsOnTheBackpack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsOnTheBackpackActionPerformed(evt);
            }
        });
        helpMenuBar.add(itemsOnTheBackpack);
        
        itemsDescription.setText(" \n Room Items Description");
        itemsDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsDescriptionActionPerformed(evt);
            }
        });
        helpMenuBar.add(itemsDescription);

        biomaDescription.setText(" \n Bioma Description");
        biomaDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biomaDescriptionActionPerformed(evt);
            }
        });
        helpMenuBar.add(biomaDescription);

        directions.setText(" \n Directions");
        directions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directionsActionPerformed(evt);
            }
        });
        helpMenuBar.add(directions);

        jMenuBar1.add(helpMenuBar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(westPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(southPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttomsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mapLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(westPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(mapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(centerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(southPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttomsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(mapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        
                textCommands.addMouseListener(new MouseAdapter() {
             public void mouseClicked(MouseEvent e) {
                textCommands.setText("");
             }
        });

        pack();
    }// </editor-fold>                        

    private void eastButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
       game.callGoRoom(new Command("go", "east"));
    }                                          
                         
    private void northButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        game.callGoRoom(new Command("go", "north"));
    }                                           

    private void southButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        game.callGoRoom(new Command("go", "south"));
    }                                           

    private void westButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        game.callGoRoom(new Command("go", "west"));
    }                                          

    private void easyButtonActionPerformed(java.awt.event.ActionEvent evt) {
        game.menu(1);
        easyButton.setEnabled(false);
        mediumButton.setEnabled(false);
        hardButton.setEnabled(false);
    }                                          

    private void mediumButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        game.menu(2);
        easyButton.setEnabled(false);
        mediumButton.setEnabled(false);
        hardButton.setEnabled(false);
    }                                            

    private void hardButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        game.menu(3);
        easyButton.setEnabled(false);
        mediumButton.setEnabled(false);
        hardButton.setEnabled(false);
    }                                
    
    private void cleanTerminalButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
       terminalTextArea.setText("");
    }                                                   
                                           

    private void putButtonActionPerformed(java.awt.event.ActionEvent evt) {
        game.callProcessCommand(new Command("put", textCommands.getText()));
    }                                             

    
    private void takeButtonActionPerformed(java.awt.event.ActionEvent evt) { 
         game.callProcessCommand(new Command("take", textCommands.getText()));
    }                                          

    
    private void itemsOnTheBackpackActionPerformed(java.awt.event.ActionEvent evt) {                                         
           game.HelpItemsOnBackpack();
    }                                        
    
    private void itemsInTheRoomActionPerformed(java.awt.event.ActionEvent evt) {                                         
           game.HelpItemsInTheRoom();
    }                                        
    
    private void itemsDescriptionActionPerformed(java.awt.event.ActionEvent evt) {                                         
           game.HelpItemsDescription();
    }   
    
      private void biomaDescriptionActionPerformed(java.awt.event.ActionEvent evt) {                                         
           game.HelpBiomaDescription();
    } 

       private void directionsActionPerformed(java.awt.event.ActionEvent evt) {                                         
           game.HelpDirections();
    }  
       
    private void optionOneActionPerformed(java.awt.event.ActionEvent evt) {
        jDialog2.setVisible(false);
        if(game.getDanger().isDeforestation()){
            game.getDanger().switchDeforestation(game.getPlayer(), 1);
        }else if(game.getDanger().isFire()){
            game.getDanger().switchcontrolFire(game.getPlayer(), 1);
        }else if(game.getDanger().isHunter()){
            game.getDanger().switcharrestHunter(game.getPlayer(), 1);
        }
        game.getmP().stop();
        game.getmP().startPlaying(game.getArrayTrack().get(5).getFilename());
        optionTextArea.setText("");
    }    
        
     private void optionTwoActionPerformed(java.awt.event.ActionEvent evt) {
         jDialog2.setVisible(false);
         if(game.getDanger().isDeforestation()){
             game.getDanger().switchDeforestation(game.getPlayer(), 2);
         }else if(game.getDanger().isFire()){
             game.getDanger().switchcontrolFire(game.getPlayer(), 2);
         }else if(game.getDanger().isHunter()){
             game.getDanger().switcharrestHunter(game.getPlayer(), 2);
         }
         game.getmP().stop();
         game.getmP().startPlaying(game.getArrayTrack().get(5).getFilename());
         optionTextArea.setText("");
    }    
            
    private void optionThreeActionPerformed(java.awt.event.ActionEvent evt) {
        jDialog2.setVisible(false);
        if(game.getDanger().isDeforestation()){
            game.getDanger().switchDeforestation(game.getPlayer(), 3);
        }else if(game.getDanger().isFire()){
            game.getDanger().switchcontrolFire(game.getPlayer(), 3);
        }else if(game.getDanger().isHunter()){
            game.getDanger().switcharrestHunter(game.getPlayer(), 3);
        }
        game.getmP().stop();
        game.getmP().startPlaying(game.getArrayTrack().get(5).getFilename());
        optionTextArea.setText("");
    }   
       
    public javax.swing.JTextArea getTerminalTextArea(){
        return terminalTextArea;
    }
       
    public javax.swing.JLabel getOxygenBarPercent(){
        return oxygenBar;
    }
    public void openMapActionPerformed(java.awt.event.ActionEvent evt) {                                           
        mapLabel.setVisible(true);
    } 
    
    public void closeMapActionPerformed(java.awt.event.ActionEvent evt) {                                           
        mapLabel.setVisible(false);
    } 
    
    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {  
       game.getmP().startPlaying(game.getArrayTrack().get(5).getFilename());
    }                                          

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
     game.getmP().stop();
    }                        
    
    public javax.swing.JDialog getjDialog2(){
        return jDialog2;
    }
    
    public javax.swing.JTextArea getOptionTextArea(){
        return optionTextArea;
    }

    public JButton getEastButton() {
        return eastButton;
    }

    public JButton getNorthButton() {
        return northButton;
    }

    public JButton getSouthButton() {
        return southButton;
    }

    public JButton getWestButton() {
        return westButton;
    }

    public JButton getPutButton() {
        return putButton;
    }
    
      public JButton getTakeButton() {
        return putButton;
    }

    public javax.swing.JMenu getHelpMenuBar() {
		return helpMenuBar;
	}

    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem directions;
    private javax.swing.JMenuItem biomaDescription;
    private javax.swing.JPanel buttomsPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JMenuItem closeMap;
    private javax.swing.JButton eastButton;
    private javax.swing.JButton easyButton;
    private javax.swing.JButton hardButton;
    private javax.swing.JMenu helpMenuBar;
    private javax.swing.JMenuItem itemsInTheRoom;
    private javax.swing.JMenuItem itemsOnTheBackpack;
    private javax.swing.JLabel mapLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu mapMenuBar;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JButton mediumButton;
    private javax.swing.JButton northButton;
    private javax.swing.JMenuItem openMap;
    private javax.swing.JButton southButton;
    private javax.swing.JPanel southPanel;
    private javax.swing.JButton putButton;
    private javax.swing.JButton takeButton;
    private javax.swing.JTextArea terminalTextArea;
    private javax.swing.JTextArea textCommands;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JButton westButton;
    private javax.swing.JPanel westPanel;
    private javax.swing.JLabel oxygenBar;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JTextArea optionTextArea;
    private javax.swing.JButton optionThree;
    private javax.swing.JButton optionTwo;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton optionOne;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JButton playButton;
    private javax.swing.JButton pauseButton;
    private javax.swing.JMenuItem itemsDescription;
    private javax.swing.JButton cleanTerminalButton;
    
    // End of variables declaration                   
}